[package]
name = "root"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true

[dev-dependencies]
redbit = { path = "redbit" }
trybuild = "1.0"
redb = "2.6.2"
bincode = "2.0.1"
axum = { version = "0.8.4", features = ["default", "macros"] }
utoipa = { version = "5.3.1", features = ["axum_extras", "debug"] }
utoipa-axum = { version = "0.2.0" ,features = ["debug"] }
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.45.1", features = ["full"] }

[workspace]
members = ["macros", "redbit", "syncer", "examples/demo", "examples/cardano", "examples/btc", "examples/ergo"]
