[package]
name = "root"
version = "0.1.0"
edition = "2021"

publish = false

[dev-dependencies]
redbit = { path = "redbit" }
trybuild = "1.0"
redb = "2.4.0"
utxo = { path = "examples/utxo" }
rand = "0.9.0"

[workspace]
members = ["macros", "redbit", "examples/utxo"]
