[package]
name = "root"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true

[dev-dependencies]
redbit = { path = "redbit" }
trybuild = "1.0"
redb = "2.6.0"
serde = { version = "1.0.219", features = ["derive"] }

[workspace]
members = ["macros", "redbit", "examples/utxo"]
