[indexer]
name = "ergo"
db_path = "/tmp/chain-syncer"
enable = true
db_cache_size_gb = 16           # redb cache size in GigaBytes
min_batch_size = 1000           # Sum of : inputs + outputs + assets/tokens
processing_parallelism = "mild" # low / mild / high

[http]
enable = true
bind_address = "127.0.0.1:3031"
