[indexer]
name = "cardano"
db_path = ".chain"
enable = true
sync_interval_s = 1             # 0 means only chatching up but no periodic sync
fork_detection_heights = 100    # max 255, how many blocks from tip to check for forks
db_cache_size_gb = 16           # 0 means disabled, redb cache size in GigaBytes
min_batch_size = 1000           # Sum of : inputs + outputs + assets/tokens
processing_parallelism = "mild" # low / mild / high

[http]
enable = true
bind_address = "127.0.0.1:3032"
