[indexer]
name = "cardano"
db_path = ".chain-syncer"
enable = true
sync_interval_s = 1             # 0 means only chatching up but no periodic sync
db_cache_size_gb = 16           # redb cache size in GigaBytes
min_batch_size = 1000           # Sum of : inputs + outputs + assets/tokens
processing_parallelism = "mild" # low / mild / high

[http]
enable = true
bind_address = "127.0.0.1:3032"
