[indexer]
name = "ergo"
db_path = "/opt/.chain"
enable = true
node_sync_interval_s = 1           # 0 means only chatching up but no periodic sync
fork_detection_heights = 100       # max 255, how many blocks from tip to check for forks
db_cache_size_gb = "mild"          # off / tiny / low / mild / high / ultra
min_entity_batch_size = 1_000_000  # Sum of : inputs + outputs
non_durable_batches = 50           # how many batches to commit non-durably before forcing a durable commit
processing_parallelism = "high"    # off / tiny / low / mild / high / ultra
validation_from_height = 0

[http]
enable = true
bind_address = "0.0.0.0:3031"
