[indexer]
name = "btc"
db_path = "/opt/.chain"
enable = true
sync_interval_s = 1             # 0 means only chatching up but no periodic sync
fork_detection_heights = 100    # max 255, how many blocks from tip to check for forks
db_cache_size_gb = 8            # 0 means disabled, redb cache size in GigaBytes
min_batch_size = 1000           # Sum of : inputs + outputs
processing_parallelism = "high"  # off / low / mild / high
validation_from_height = 0

[http]
enable = true
bind_address = "127.0.0.1:3033"
