[package]
name = "macros"
version = "1.0.2"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro-error = "1"
syn = "2"
quote = "1"
proc-macro2 = "1"
prettyplease = "0.2.29"
strum = "0.27.2"
strum_macros = "0.27.2"