[package]
name = "utxo"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true

[[bench]]
name = "utxo"
harness = false

[dev-dependencies]
criterion = "0.6.0"

[dependencies]
rand = "0.9.0"
redbit = { path = "../../redbit" }
serde = { version = "1.0.217", features = ["derive"] }
tokio = { version = "1.45.1", features = ["full"] }
inventory = "0.3.20"