[package]
name = "utxo"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true

[[bench]]
name = "utxo"
harness = false

[dev-dependencies]
rand = "0.9.0"
criterion = "0.5"

[dependencies]
redbit = { path = "../../redbit" }
redb = "2.4.0"
serde = { version = "1.0.217", features = ["derive"] }